# alembic/versions/b57819918d9d_mensaje_de_la_migración.py

"""Mensaje de la migraciÃ³n

Revision ID: b57819918d9d
Revises: 
Create Date: 2023-10-31 07:48:34.461473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b57819918d9d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Articulos',
    sa.Column('id_articulo', sa.String(length=64), nullable=False),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_articulo')
    )
    op.create_table('Proyectos',
    sa.Column('id_proyecto', sa.String(length=32), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id_proyecto')
    )
    op.create_table('Vertices',
    sa.Column('id_vertice', sa.String(length=32), nullable=False),
    sa.Column('id_proyecto', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['id_proyecto'], ['Proyectos.id_proyecto'], ),
    sa.PrimaryKeyConstraint('id_vertice')
    )
    op.create_table('Bogies',
    sa.Column('matricula', sa.String(length=32), nullable=False),
    sa.Column('id_vertice', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['id_vertice'], ['Vertices.id_vertice'], ),
    sa.PrimaryKeyConstraint('matricula')
    )
    op.create_table('Kits',
    sa.Column('id_kit', sa.String(length=64), nullable=False),
    sa.Column('id_vertice', sa.String(length=32), nullable=True),
    sa.Column('edicion', sa.Integer(), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('va_a_linea', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_vertice'], ['Vertices.id_vertice'], ),
    sa.PrimaryKeyConstraint('id_kit')
    )
    op.create_table('Articulos_Kits',
    sa.Column('id_articulo_kit', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_articulo', sa.String(length=64), nullable=True),
    sa.Column('id_kit', sa.String(length=64), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_articulo'], ['Articulos.id_articulo'], ),
    sa.ForeignKeyConstraint(['id_kit'], ['Kits.id_kit'], ),
    sa.PrimaryKeyConstraint('id_articulo_kit')
    )
    op.create_table('Faltas',
    sa.Column('id_falta', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('matricula_bogie', sa.String(length=32), nullable=True),
    sa.Column('id_articulo_kit', sa.Integer(), nullable=True),
    sa.Column('cantidad_faltante', sa.Integer(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['id_articulo_kit'], ['Articulos_Kits.id_articulo_kit'], ),
    sa.ForeignKeyConstraint(['matricula_bogie'], ['Bogies.matricula'], ),
    sa.PrimaryKeyConstraint('id_falta')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Faltas')
    op.drop_table('Articulos_Kits')
    op.drop_table('Kits')
    op.drop_table('Bogies')
    op.drop_table('Vertices')
    op.drop_table('Proyectos')
    op.drop_table('Articulos')
    # ### end Alembic commands ###
